// API reference data for the docs site, read straight from the TypeScript source.
//
//   node scripts/api-docs.mjs            -> site/generated/api.json
//   node scripts/api-docs.mjs --stdout   -> api.json to stdout
//
// Every JS subpath in package.json `exports` is mapped to its source entry ("." -> src/index.ts,
// "./<name>" -> src/<name>/index.ts) and each export is classified as component, function,
// class, type or const. Messages come from the string tables in src/**/messages.ts.
// The output is gitignored and regenerated by the site scripts.
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import ts from "typescript";
import { tsImport } from "tsx/esm/api";
import {
  GLOBAL_TYPES,
  createProgram,
  destructuringDefaults,
  docText,
  functionNode,
  isOurs,
  tagsOf,
  typeText,
} from "./api-docs/ts-helpers.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = join(root, "src");

/** Subpath -> source entry; undefined for CSS subpaths. */
function entryFile(subpath) {
  if (subpath.endsWith(".css")) return undefined;
  return subpath === "." ? join(src, "index.ts") : join(src, subpath.slice(2), "index.ts");
}

const deprecatedOf = (tags) => ("deprecated" in tags ? tags.deprecated || true : false);

function membersOf(type, symbolType, checker, location, publicNames) {
  const members = [];
  for (const prop of type.getProperties()) {
    const decl = prop.declarations?.[0];
    if (decl == null || !isOurs(decl)) continue;
    const tags = tagsOf(prop, checker);
    members.push({
      name: prop.getName(),
      type: typeText(prop, checker, location, publicNames),
      required: !(prop.flags & ts.SymbolFlags.Optional),
      default: tags.default ?? null,
      description: docText(checker, prop),
      deprecated: deprecatedOf(tags),
    });
  }
  return members;
}

function isPublicInstanceProperty(prop) {
  const decl = prop.declarations?.[0];
  if (decl == null || !isOurs(decl)) return false;
  if (!(ts.isPropertyDeclaration(decl) || ts.isParameter(decl) || ts.isGetAccessor(decl)))
    return false;
  const flags = ts.getCombinedModifierFlags(decl);
  return !(
    flags &
    (ts.ModifierFlags.Private | ts.ModifierFlags.Protected | ts.ModifierFlags.Static)
  );
}

function describeExport(exported, checker, publicNames) {
  const name = exported.getName();
  const target =
    exported.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(exported) : exported;
  const declaration = target.declarations?.[0];
  if (declaration == null) return undefined;
  const tags = tagsOf(target, checker);
  const base = {
    name,
    file: relative(root, declaration.getSourceFile().fileName),
    description: docText(checker, target),
    deprecated: deprecatedOf(tags),
  };

  if (target.flags & ts.SymbolFlags.Class) {
    const instance = checker.getDeclaredTypeOfSymbol(target);
    const members = membersOf(
      { getProperties: () => instance.getProperties().filter(isPublicInstanceProperty) },
      instance,
      checker,
      declaration,
      publicNames,
    );
    return { ...base, kind: "class", signature: `class ${name}`, members };
  }

  if (target.flags & (ts.SymbolFlags.Interface | ts.SymbolFlags.TypeAlias)) {
    const declared = checker.getDeclaredTypeOfSymbol(target);
    const typeParams =
      ts.isTypeAliasDeclaration(declaration) || ts.isInterfaceDeclaration(declaration)
        ? (declaration.typeParameters?.map((p) => p.getText()).join(", ") ?? "")
        : "";
    const head = `${name}${typeParams ? `<${typeParams}>` : ""}`;
    const objectLike =
      ts.isInterfaceDeclaration(declaration) ||
      (ts.isTypeAliasDeclaration(declaration) && ts.isTypeLiteralNode(declaration.type));
    if (objectLike) {
      return {
        ...base,
        kind: "type",
        signature: `type ${head}`,
        members: membersOf(declared, declared, checker, declaration, publicNames),
      };
    }
    const text = ts.isTypeAliasDeclaration(declaration)
      ? declaration.type.getText().replace(/\s+/g, " ")
      : name;
    return { ...base, kind: "type", signature: `type ${head} = ${text}`, members: [] };
  }

  if (target.flags & (ts.SymbolFlags.Function | ts.SymbolFlags.Variable)) {
    const type = checker.getTypeOfSymbolAtLocation(target, declaration);
    const signatures = type.getCallSignatures();
    if (signatures.length === 0) {
      const text = checker.typeToString(type, undefined, ts.TypeFormatFlags.NoTruncation);
      return { ...base, kind: "const", signature: `const ${name}: ${text}`, members: [] };
    }
    const signature = `${name}${checker.signatureToString(signatures[0])}`;
    if (/^[A-Z]/.test(name) && signatures.length === 1 && signatures[0].parameters.length <= 1) {
      const param = signatures[0].parameters[0];
      const propsType = param ? checker.getTypeOfSymbolAtLocation(param, declaration) : undefined;
      const defaults = destructuringDefaults(functionNode(declaration), checker);
      const members = propsType
        ? membersOf(propsType, propsType, checker, declaration, publicNames)
        : [];
      for (const m of members) m.default ??= defaults[m.name] ?? null;
      return { ...base, kind: "component", signature, members };
    }
    return { ...base, kind: "function", signature, members: [] };
  }
  return undefined;
}

/** All `<area>Messages` tables (en + zh-TW) found in src/**\/messages.ts, as sorted flat rows. */
async function messageRows() {
  const files = [];
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) walk(join(dir, entry.name));
      else if (entry.name === "messages.ts") files.push(join(dir, entry.name));
    }
  };
  walk(src);
  files.sort();
  const rows = [];
  for (const file of files) {
    const mod = await tsImport(pathToFileURL(file).href, import.meta.url);
    for (const [name, table] of Object.entries(mod)) {
      if (!name.endsWith("Messages") || table?.en == null || table?.["zh-TW"] == null) continue;
      for (const key of Object.keys(table.en)) {
        rows.push({ key, en: table.en[key], "zh-TW": table["zh-TW"][key] });
      }
    }
  }
  return rows.sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0));
}

export async function apiDocs() {
  const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
  const subpaths = Object.keys(pkg.exports).filter((s) => entryFile(s) != null);
  const program = createProgram(root, subpaths.map(entryFile));
  const checker = program.getTypeChecker();
  const modules = subpaths.map((subpath) => {
    const file = entryFile(subpath);
    const moduleSymbol = checker.getSymbolAtLocation(program.getSourceFile(file));
    return { subpath, file, exports: checker.getExportsOfModule(moduleSymbol) };
  });
  const publicNames = new Set([
    ...GLOBAL_TYPES,
    ...modules.flatMap((m) => m.exports.map((s) => s.getName())),
  ]);
  const entries = modules.map(({ subpath, file, exports }) => ({
    subpath,
    importPath: subpath === "." ? pkg.name : `${pkg.name}/${subpath.slice(2)}`,
    file: relative(root, file),
    exports: exports
      .map((s) => describeExport(s, checker, publicNames))
      .filter((e) => e != null)
      .sort((a, b) => a.name.localeCompare(b.name)),
  }));
  return { generatedFrom: "package.json#exports", entries, messages: await messageRows() };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const api = await apiDocs();
  if (process.argv.includes("--stdout")) {
    process.stdout.write(`${JSON.stringify(api, null, "\t")}\n`);
  } else {
    const out = join(root, "site/generated");
    mkdirSync(out, { recursive: true });
    writeFileSync(join(out, "api.json"), `${JSON.stringify(api, null, "\t")}\n`);
    const exportCount = api.entries.reduce((n, e) => n + e.exports.length, 0);
    console.log(
      `${api.entries.length} entries, ${exportCount} exports, ${api.messages.length} messages`,
    );
  }
}
